---
name: Build packages

on:
    push:
        branches:
            - master
    pull_request:

concurrency:
    # resolves to the caller workflow: ${{ github.workflow }}
    group: build_packages_${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    packages:
        strategy:
            matrix:
                os: [ubuntu-jammy]
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v3
        - uses: legoktm/gh-action-build-deb@ubuntu-jammy
          with:
            args: --no-sign
        - uses: actions/upload-artifact@v3
          with:
            name: Packages for ${{matrix.os}}
            path: output
