#!/usr/bin/env python3

""" github does not support ${{matrix.foo}} eval at job level in `uses`
"""

import os
import jinja2

tpl = r"""# THIS FILE IS AUTOGENERATED -- DO NOT EDIT             #
#   Edit and Re-run  .github/workflows/build_packages.py  instead #

---
name: Build packages

on:
    push:
        branches:
            - master
    pull_request:

jobs:
{% for job, os in job_os %}
    {{job}}:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v3
        - uses: legoktm/gh-action-build-deb@{{os}}
          with:
            args: --no-sign
        - uses: actions/upload-artifact@v3
          with:
            name: flexiblas_{{os}}
            path: output
{% endfor %}

    deploy:
        runs-on: ubuntu-22.04
        needs:
        {% for job,os in job_os -%}
        - {{job}}
        {% endfor %}
        steps:
        - uses: actions/download-artifact@v3
          id: download
          with:
            path: output/releases/3.2.1
        - uses: actions/upload-artifact@v3
          with:
            name: flexiblas_3.2.1_debs
            path: output



# THIS FILE IS AUTOGENERATED -- DO NOT EDIT                     #
#   Edit and Re-run .github/workflows/build_packages.py instead #

"""  # noqa


tpl = jinja2.Template(tpl)

# buster does not have the right build time deps
job_os = [
    ("jammy", "ubuntu-jammy"),
    ("kinetic", "ubuntu-kinetic"),
    ("focal", "ubuntu-focal"),
    ("bullseye", "debian-bullseye"),
]

with open(os.path.join(os.path.dirname(__file__), "build_packages.yml"), "wt") as yml:
    yml.write(tpl.render(**locals()))
